In [1]:
import numpy as np

Create a table (i.e. a 2d array) of size M x N filled with random integers between 1 and 100,
where 1 < N < 40 and 1 < M < 50.

In [22]:
M = np.random.randint(1,50)
N = np.random.randint(1,40)

a = np.random.randint(1, 100, size=(N, M))
a

array([[79, 18, 46, ..., 24, 98, 83],
       [35, 86, 36, ..., 62, 13, 82],
       [58, 42, 14, ..., 54, 35, 60],
       ...,
       [46, 71, 33, ..., 22, 80, 45],
       [73, 67, 63, ..., 62, 10, 18],
       [28, 22, 31, ..., 71,  2, 79]])

In [23]:
a[2]

array([58, 42, 14, 40, 47, 49, 87, 65, 81, 43, 22, 53, 54, 48, 74, 83,  1,
       49, 72, 77, 65,  5, 71, 90, 85,  7, 65, 75, 17, 99, 15, 28, 14, 86,
       76, 31,  8, 61, 15, 84, 81, 54, 35, 60])

In [24]:
a[:,2]

array([46, 36, 14, 82, 42, 76, 50, 79, 62, 89, 17, 47, 99, 58, 54, 98, 65,
       10, 84,  9, 47, 53, 33, 63, 31])

In [30]:
a[-1] = 7
a[-1]

In [48]:
a[:,-1] == np.sum(a[0] + a[1])

a[:,-1]

array([287898, 287898, 287898, 287898, 287898, 287898, 287898, 287898,
       287898, 287898, 287898, 287898, 287898, 287898, 287898, 287898,
       287898, 287898, 287898, 287898, 287898, 287898, 287898, 287898,
       287898])