In [1]:
import numpy as np

In [2]:
one_dim_array = np.array([1,2,3,4,5,6])

In [23]:
2

2

In [24]:
print(np.__version__)

1.23.1


In [25]:
3

3

In [26]:
np.zeros((10,), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
4

4

In [28]:
array1 = np.array([1,2,3,4,5])
print(array1.itemsize)

8


In [29]:
5

5

In [30]:
np.add(1.0, 4.0)

5.0

In [31]:
np.?add(1.0, 4.0)

SyntaxError: invalid syntax (3369977852.py, line 1)

In [32]:
6

6

In [33]:
np.zeros((10,), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
x = np.zeros((10,), dtype=int)
x[5] = 1

In [38]:
x

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [39]:
7

7

In [41]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [42]:
8

8

In [44]:
array1[::-1]

array([5, 4, 3, 2, 1])

In [45]:
9

9

In [46]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
10

10

In [48]:
a = np.array([1,2,0,0,4,0])
print(a.nonzero())

(array([0, 1, 4]),)


In [49]:
11


11

In [50]:
array2 = np.identity(3)

In [51]:
array2 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
12

12

In [58]:
random_array =  np.random.randint(10,90)

In [59]:
random_array

51

In [60]:
rand_int = np.random.randint(5,10)  
print("First array", rand_int)

First array 9


In [61]:
12

12

In [62]:
np.random.rand(3,3)

array([[0.85962798, 0.63254465, 0.62383629],
       [0.07861373, 0.93943706, 0.00164414],
       [0.54181316, 0.16717512, 0.16192088]])

In [63]:
13

13

In [64]:
a = np.random.rand(10,10)

In [65]:
a.min()

0.0065077710949608125

In [66]:
a.max()

0.9920551421305626

In [67]:
k = np.random.random(30)

In [68]:
k

array([0.89306754, 0.37090208, 0.7293239 , 0.76471029, 0.50719015,
       0.44128915, 0.61085915, 0.16383828, 0.2152368 , 0.0624815 ,
       0.77120476, 0.27524157, 0.32664122, 0.0212013 , 0.82466896,
       0.39033935, 0.865657  , 0.27614056, 0.94530446, 0.24212203,
       0.21557206, 0.38289646, 0.19100603, 0.75543879, 0.78353298,
       0.62906881, 0.61321508, 0.55995534, 0.3653183 , 0.0383191 ])

In [69]:
k.mean()

0.47439143457306704

In [70]:
15

15

In [83]:
s = np.ones((3,3), dtype=int)
s

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [84]:
s[1:-1,1:-1] = 0

In [85]:
s

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [86]:
16

16

In [90]:
np.pad(s,pad_width=1, constant_values=0)

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [91]:
17

17

In [92]:
0 * np.nan

nan

In [93]:
np.nan == np.nan

False

In [94]:
np.inf > np.nan

False

In [95]:
np.nan - np.nan

nan

In [96]:
0.3 == 3 * 0.1

False

18

In [97]:
# 18

In [99]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

19


In [135]:
w = np.ones((8,8), dtype=int)
w[1::2,::2] = 0
w[::2,1::2] = 0

In [136]:
w

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

20

In [137]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

21

In [147]:
d = np.array([[0,1],[1,0]])
np.tile(d,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

22

In [152]:
e = np.random.random((5,5))
min_val = e.min()
max_val = e.max()
e = (e - min_val)/(max_val-min_val)
e

array([[0.36663391, 0.832183  , 0.176749  , 0.60221351, 0.4833918 ],
       [0.85086781, 0.61372504, 0.39949942, 0.8294475 , 0.12192348],
       [0.40741425, 0.90165533, 0.4685659 , 0.        , 0.81085155],
       [0.11939182, 0.10770088, 0.35162151, 0.98193743, 0.93542094],
       [1.        , 0.54058959, 0.780336  , 0.02623058, 0.22954799]])

23

In [163]:
n = np.array([1,2,3,4,5,6,7,8])
n = n.astype(np.int16)
n

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int16)

24


In [164]:
a = np.arange(15).reshape((5,3)) 
b = np.arange(6).reshape((3,2))
np.dot(a, b)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

25

In [169]:
ar = np.arange(20)
n = (ar > 3) & (ar <= 8)
ar[n] *= -1
ar

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

26

In [174]:
print(sum(range(5),-1))

9


In [179]:
print(sum(range(5),-1)) 
from numpy import * 
print(sum(range(5),-1))

10
10


27

In [180]:
z**z


NameError: name 'z' is not defined

28

In [181]:
np.array(0) / np.array(0)


/var/folders/57/9550yncd7lv1xs7348_ffjbr0000gn/T/ipykernel_48200/3272234849.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [182]:
+


SyntaxError: invalid syntax (3168125227.py, line 1)

In [183]:
np.array(0) // np.array(0)

/var/folders/57/9550yncd7lv1xs7348_ffjbr0000gn/T/ipykernel_48200/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [184]:
+


SyntaxError: invalid syntax (3168125227.py, line 1)

29

In [187]:
o = np.array([1.1,2.2,3.3])
np.round(o,0)

array([1., 2., 3.])

30

In [189]:
np.intersect1d([1,2,3,4,5],[1,6,4,8,9,3])

array([1, 3, 4])

31

In [195]:

np.seterr(all="ignore")


0.29008086429026286

32

In [196]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [197]:
-

SyntaxError: invalid syntax (476313318.py, line 1)

33

In [201]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1,'D')

numpy.datetime64('2022-08-01')

34

In [ ]:
np.arange('2016-07', '2016')