In [48]:
import numpy as np
import pandas as pd
import ssl
ssl._create_default_https_context = ssl._create_unverified_context


1
Write a function to create a numpy array using only the input: start, length, and stop.
Use the function to create an numpy array of length 100, starting from 6 and has a step of 4 between consecutive numbers

In [20]:
def create_array(start,length,step):
    stop = (length+1) * step
    return np.arange(start = start, stop = stop, step = step)
create_array(6,100,4)

array([ 6, 10, 14, 18, 22, 26, 30, 34, 38, 42])

2.
Drop all nan values from the following numpy array.

In [21]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a = a[~np.isnan(a)]
a

array([1., 2., 3., 5., 6., 7.])

3.
create a random numpy array that has a shape of (5, 6) filled with integers between 1 and 100. 
Then compute the maximum int for each row in the array

In [38]:
a = np.random.randint(100, size=(5,6))
a.max(axis=1)

array([81, 78, 87, 90, 92])

4
use a pandas Series function to find the unique values and their frequencies of the following Series:

In [40]:
series = pd.Series(np.take(list('abcdefghijklmnop'), np.random.randint(16, size=500)))
series.value_counts()

d    48
m    46
k    38
g    36
h    36
e    36
j    31
n    29
i    29
a    27
f    27
b    25
o    23
c    23
p    23
l    23
dtype: int64

6
Read the data from https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv into a pandas dataframe. 
Do not download the file.

Then 
- print how many columns are of each datatype.
- Change the column name “Type” to “TypeOfCar” and print the head of the dataframe

How many values are missing from each of the columns?
Which columns has the most missing values? (answer with code, without sorting)

In [52]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.dtypes.value_counts()

float64    18
object      9
dtype: int64

In [57]:
df.rename(columns={'Type' : 'TypeOfCar'},inplace=True)

In [60]:
df.isna().sum()

Manufacturer           4
Model                  1
TypeOfCar              3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [64]:
df.isna().sum().idxmax()


'Luggage.room'

7
Delete the columns: “EngineSize” and “Length” in 2 different ways. Check (with code) that these columns are indeed gone

In [65]:
df = df.drop('EngineSize', axis=1)

In [67]:
del df['Length']

8.

Join the following two dataframes by two columns, so they have only the common rows. Remove duplicate
columns (meaning that all values are the same) to keep only one.

In [69]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

In [70]:
df_joined = df1.merge(df2,left_on=('fruit','weight'),right_on=('pazham','kilo'),how='inner',suffixes=('_left','_right'))

In [73]:
df_joined.drop_duplicates(subset='fruit')

fruit weight  price_left  pazham  kilo  price_right
0   apple   high           3   apple  high            7
3  orange    low          12  orange   low           13

9
Split this dataframe with a string column to form a dataframe with 3 columns named “STD”, “City”, and “State.”

In [84]:
df9 = pd.DataFrame(["STD,City\tState",
"33,Kolkata\tWest Bengal",
"44,Chennai\tTamil Nadu",
"40,Hyderabad\tTelengana",
"80,Bangalore\tKarnataka"], columns=['row'])


In [97]:
new_df = df["row"].str.split("\t|,", n=2, expand=True)
new_df



0          1            2
0  STD       City        State
1   33    Kolkata  West Bengal
2   44    Chennai   Tamil Nadu
3   40  Hyderabad    Telengana
4   80  Bangalore    Karnataka